---
- hosts: 172.31.18.4
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: copy index file into nodes''
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
  - name: i want to download remote files
    get_url:
      url: https://get.jenkins.io/war/2.329/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes

