---
- hosts: all
  become: yes
  gather_facts: yes
    tasks:
  - name: i want to install git
    apt:
      name: git
      state: present 
  - name: i want to install a tree
    apt:
        name: tree
        state: present
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
  - name: i want to start mywebserver
    service:
        name: apache2
        state: started
