---
- hosts: all
  become: yes
  tasks:
  - name: i want to install ubuntu 16 server
    apt: 
      name: "{{mywebpackageonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: i want to start webservers on nodes
    service:
      name: "{{mywebpackageonubuntu}}"
      state: started
    when: ansible_os_family =="Debian"
  - name: i want to install webser in redhat
    yum:
      name: "{{mywebpackageonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: i want to start webserver on redhat nodes
    service:
      name: "{{mywebpackageonredhat}}"
      state: started
    when: ansible_os_family =="RedHat"

